---
driver:
  name: vagrant
  customize:
    memory: 8192
    cpus: 2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: "12"

verifier:
  name: inspec

platforms:
    - name: grtjn/centos-6.5

suites:
  - name: default
    run_list:
       - recipe[chef_ambari::ambari_pre_config]
       - recipe[chef_ambari::ambari_hdp_setup]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
